# Site
repository: #SamuelChan123/SamuelChan123.github.io
favicon: ../images/favicon.ico

# Personal info
name: Samuel P. Chan
title: Software Engineer
email: samuelchaneiusgloria@gmail.com
phone: (410) 428-2378
website: SamuelChan123.github.io

darkmode: never

# Social links
github_username: SamuelChan123
linkedin_username: samuelpchan

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: ../images/profile.img
about_content: | # this will include new lines to allow paragraphs
  Hey there! My name is Sam and I'm a software engineer graduating from Duke in May 2021 with a B.S. in Computer Science. 

  I've always been really fascinated and passionate about how tech and social good can intersect, and I'm constantly looking for opportunities
  to make a difference in the world :)

  Some of my hobbies include: playing and watching sports (especially basketball), discussing politics, 
  hanging out with friends and family, hiking/camping, and watching Christopher Nolan movies.
# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Work Experience #(Use this to override about experience section title)

# Education Section
education_title: Education #(Use this to override about education section title)

# More Section
more_title: Organizations/Interests #Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - HackDuke Planning Team Co-Director 2019, Outreach/Logistics Lead 2018/2020: 
    1. Organized the annual Code for Good collegiate hackathon, drawing 600+ students from across the nation to ideate about 140 projects that aim to positively impact our social environment
    2. Collaborated with 25+ teammates to reach out to 20 companies and secure a total of over $40k in sponsorship, coordinate team events, manage logistics, speak directly with corporate representatives and Duke University administration
    3. Directly reached out to and coordinated with total of 10+ professors, 30+ company recruiters and speakers, implemented eries of 10+ workshops before and during the hackathon to educate 200+ students about technical and out-of-classroom skills
  - The Cube (Innovation & Entrepreneurship Selective Living Group)
  - Duke Effective Altruism (Arete Fellowship)
  - Intramural Sports (Basketball, Volleyball, Wallyball, Frisbee)
  - Duke InterVarsity (Afterhours Social Team)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
